# Generated by Django 5.0.4 on 2024-04-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylish_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexem',
            name='style',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lexem',
            name='word',
            field=models.TextField(),
        ),
    ]
